version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "PathfinderHonorManager"
      - "PathfinderHonorManager.Tests"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
