version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/PathfinderHonorManager"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "nuget"
    directory: "/PathfinderHonorManager.Tests"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

